
alias ls='ls -G'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

if [ -x "$HOME/bin/git-ps1.sh" ]; then
    PS1="$PS1\$($( cat $HOME/bin/git-ps1.sh ))"
fi

for completion in "/usr/local/etc/bash_completion.d/*"
do
    source $completion
done
